# -*- coding: utf-8 -*-
"""Cópia de Exércicio01_IC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/168lytFl8RBzBj9s6HsW08zZXeaFaZhi8
"""

import numpy as np
import os #Operating System - manipular diretório, arquivos e caminhos

class GeradorSeriesTemporais:
    """
    Classe para gerar e manipular séries temporais multivariadas.
    """
    def __init__(self, n_amostras=20, tam_vetor=1000): #Construtor - inicializar o estado do objeto
        """
        Inicializa o gerador.

        Args:
            n_amostras (int): Número de amostras de séries temporais (padrão: 20).
            tam_vetor (int): Tamanho do vetor de tempo (padrão: 1000).
        """
        self.n_amostras = n_amostras
        self.tam_vetor = tam_vetor
        self.tempo = np.linspace(0, 10, tam_vetor) # Vetor de tempo de 0 a 10 segundos

    def _gerar_senoides(self, amplitude, frequencia):
      #nomeclatura iniciada em _ (_gerar_senoides) indica que o método é para uso interno da classe
        """
        Gera um conjunto de senoides com a mesma amplitude e frequência.

        Args:
            amplitude (float): Amplitude da senoide.
            frequencia (float): Frequência angular (rad/s) da senoide.

        Returns:
            np.ndarray: Array 2D (n_amostras, tam_vetor) com as senoides geradas.
        """
        # Cria uma matriz 2D para armazenar todas as amostras
        senoides = np.zeros((self.n_amostras, self.tam_vetor))
        for i in range(self.n_amostras):
            # Adiciona uma pequena fase aleatória para diferenciar os sinais
            fase_aleatoria = np.random.uniform(0, 2 * np.pi) #deslocamento horizontal no gráfico, completa o ciclo de 360°
            #cada onda tem um ponto de partida (fase) diferente
            senoides[i, :] = amplitude * np.sin(frequencia * self.tempo + fase_aleatoria) # função seno: A * sin(ωt + φ)
        return senoides

    def criar_cenario(self, config_sinais, nome_arquivo):
        """
        Cria um cenário completo com 3 tipos de senoides e salva em .npy.

        Args:
            config_sinais (list of tuples): Lista contendo tuplas (amplitude, frequencia)
                                            para cada um dos 3 sinais.
            nome_arquivo (str): Nome do arquivo .npy para salvar os dados.
        """
        print(f"Gerando cenário para '{nome_arquivo}'...")

        # Gera os 3 conjuntos de 20 senoides
        senoides1 = self._gerar_senoides(config_sinais[0][0], config_sinais[0][1])
        senoides2 = self._gerar_senoides(config_sinais[1][0], config_sinais[1][1])
        senoides3 = self._gerar_senoides(config_sinais[2][0], config_sinais[2][1])

        # Empilha os 3 conjuntos para formar a matriz final (20, 3, 1000)
        # np.stack cria uma nova dimensão
        matriz_final = np.stack([senoides1, senoides2, senoides3], axis=1)

        '''Função axis - eixo determina o índice (a posição) onde a nova dimensão
        será inserida no .shape da matriz final.
        axis = 0 --> (3,20,1000)
        axis = 1 --> (20,3,1000)
        axis = 2 --> (20,1000,3) '''

        print(f"Dimensão da matriz resultante: {matriz_final.shape}")

        # Salva a matriz em um arquivo .npy
        np.save(nome_arquivo, matriz_final)
        print(f"Matriz salva em '{nome_arquivo}.npy'\n")

        return matriz_final

   
    ''' 
    Decorador - transforma em um método estático. Pertence à classe, mas não depende
        de um objeto específico (ele não recebe o self) e não precisa acessar atributos
        da instância.
        '''
    @staticmethod
    def remover_dados_mcar(dados, percentual, nome_arquivo_saida): #MCAR: Missing Completely at Random

        """
        Remove um percentual de dados de uma série temporal (mecanismo MCAR).

        Args:
            dados (np.ndarray): Matriz de dados original.
            percentual (float): Percentual de dados a serem removidos (ex: 0.10 para 10%).
            nome_arquivo_saida (str): Nome do arquivo para salvar a matriz com dados faltantes.
        """

        print(f"Removendo {percentual*100:.0f}% dos dados de '{nome_arquivo_saida}'...")

        # Cria uma cópia para não alterar o array original
        dados_com_faltantes = dados.copy()

        # Calcula o número total de elementos e quantos remover
        n_total_elementos = dados.size
        n_a_remover = int(n_total_elementos * percentual)

        # Gera uma lista de todos os índices possíveis ( achatando o array)
        indices = np.arange(n_total_elementos) #cria uma sequência de número de 0 até o total de elementos

        # Escolhe aleatoriamente os índices que serão removidos, são9 índices planos (0 a 5999)
        indices_para_remover = np.random.choice(indices, size=n_a_remover, replace=False) #replace = false --> sem repetições

        # Converte os índices "planos" de volta para coordenadas 3D
        coords_para_remover = np.unravel_index(indices_para_remover, dados.shape)
        # numpy.unravel_index(indices, shape, order='C')

        # Substitui os valores nos índices escolhidos por NaN (Not a Number)
        dados_com_faltantes[coords_para_remover] = np.nan

        # Salva o novo array
        np.save(nome_arquivo_saida, dados_com_faltantes)
        print(f"Dados com valores faltantes salvos em '{nome_arquivo_saida}.npy'\n")
        return dados_com_faltantes

# --- Execução do Script ---

if __name__ == "__main__":
    # Garante que o diretório de saída exista
    if not os.path.exists("dados_gerados"):
        os.makedirs("dados_gerados")

    gerador = GeradorSeriesTemporais(n_amostras=20, tam_vetor=1000)

    # 1. Cenário Normal
    config_normal = [
        (1.0, 10),  # amplitude, frequencia
        (0.5, 50),
        (2.0, 25)
    ]
    dados_normal = gerador.criar_cenario(config_normal, "dados_gerados/cenario_normal")

    # 2. Cenário Normal - Outra Condição de Operação
    config_normal_alt = [
        (1.1, 15),
        (0.4, 40),
        (2.5, 30)
    ]
    dados_normal_alt = gerador.criar_cenario(config_normal_alt, "dados_gerados/cenario_normal_alt")

    # 3. Cenário Anômalo
    config_anomalo = [
        (1.0, 20),
        (0.4, 25),
        (4.0, 25)
    ]
    dados_anomalo = gerador.criar_cenario(config_anomalo, "dados_gerados/cenario_anomalo")

    # 4. Remover dados de cada cenário
    cenarios = {
        "normal": dados_normal,
        "normal_alt": dados_normal_alt,
        "anomalo": dados_anomalo
    }
    percentuais_mcar = [0.10, 0.20, 0.30]

    for nome, dados in cenarios.items():
        for p in percentuais_mcar:
            nome_saida = f"dados_gerados/cenario_{nome}_mcar_{int(p*100)}p"
            GeradorSeriesTemporais.remover_dados_mcar(dados, p, nome_saida)

"""as 20 amostras:

"""

import numpy as np
import matplotlib.pyplot as plt

# --- 1. Parâmetros da Simulação ---
n_amostras = 20         # O número de ondas que queremos gerar
tam_vetor = 1000        # Número de pontos em cada onda (resolução)
amplitude = 1.5         # Amplitude (altura) de todas as ondas
frequencia = 2          # Frequência em Hertz (quantos ciclos por segundo)
tempo_total_s = 5       # Duração da simulação em segundos

# --- 2. Criação do Eixo do Tempo ---
# Cria um vetor de tempo que vai de 0 a tempo_total_s, com tam_vetor pontos.
tempo = np.linspace(0, tempo_total_s, tam_vetor)

# --- 3. Preparação do Gráfico ---
# Cria a figura e os eixos para o plot. O figsize controla o tamanho da janela.
plt.figure(figsize=(14, 8))

# --- 4. Loop Principal para Gerar e Plotar as Ondas ---
print(f"Gerando e plotando {n_amostras} ondas senoidais...")

for i in range(n_amostras):
    # O PONTO-CHAVE: Gera uma nova fase aleatória para CADA onda.
    # O valor é sorteado entre 0 e 2*pi (um ciclo completo).
    fase_aleatoria = np.random.uniform(0, 2 * np.pi)

    # Calcula a senoide usando a fórmula completa: A * sin(2*pi*f*t + phi)
    senoide = amplitude * np.sin(2 * np.pi * frequencia * tempo + fase_aleatoria)

    # Plota a onda recém-criada no gráfico.
    # O alpha=0.7 deixa as linhas um pouco transparentes para melhor visualização.
    plt.plot(tempo, senoide, alpha=0.7)

# --- 5. Finalização do Gráfico ---
# Adiciona títulos e rótulos para deixar o gráfico informativo.
plt.title(f'{n_amostras} Ondas Senoidais com Mesma Amplitude e Frequência', fontsize=16)
plt.xlabel('Tempo (s)', fontsize=12)
plt.ylabel('Amplitude', fontsize=12)
plt.grid(True) # Adiciona uma grade de fundo para facilitar a leitura.
plt.ylim(-amplitude * 1.2, amplitude * 1.2) # Define um limite vertical para o eixo Y.

# Exibe o gráfico final na tela.
plt.show()

print("Gráfico exibido com sucesso!")

"""axis:"""

import numpy as np

# Vamos criar 3 matrizes 2x4 para ficar fácil de visualizar
a = np.array([[1, 1, 1, 1],
              [2, 2, 2, 2]])

b = np.array([[3, 3, 3, 3],
              [4, 4, 4, 4]])

c = np.array([[5, 5, 5, 5],
              [6, 6, 6, 6]])

print("--- Empilhando com axis=0 ---")
stack_0 = np.stack([a, b, c], axis=0)
print(stack_0)
print("Shape resultante:", stack_0.shape, "\n") # Saída: (3, 2, 4)

print("--- Empilhando com axis=1 ---")
stack_1 = np.stack([a, b, c], axis=1)
print(stack_1)
print("Shape resultante:", stack_1.shape, "\n") # Saída: (2, 3, 4)

print("--- Empilhando com axis=2 ---")
stack_2 = np.stack([a, b, c], axis=2)
print(stack_2)
print("Shape resultante:", stack_2.shape) # Saída: (2, 4, 3)

import numpy as np

# Carregar um dos arquivos gerados (o cenário normal, por exemplo)
dados_normal = np.load('dados_gerados/cenario_normal.npy')

# Verificar o formato (shape) do array carregado
print(f"Formato do array: {dados_normal.shape}")

# Visualizar uma pequena parte dos dados
# Vamos ver os 5 primeiros pontos de tempo, do primeiro sinal, da primeira amostra
print("\nAmostra dos dados (início do sinal 0 da amostra 0):")
print(dados_normal[0, 0, :5])

# Agora, vamos carregar um arquivo com dados faltantes
dados_mcar_30p = np.load('dados_gerados/cenario_normal_mcar_30p.npy')

# Verificar quantos dados faltantes (NaN) existem
total_elementos = dados_mcar_30p.size
nan_count = np.count_nonzero(np.isnan(dados_mcar_30p))
percentual_nan = (nan_count / total_elementos) * 100

print(f"\nTotal de elementos no arquivo com 30% de dados faltantes: {total_elementos}")
print(f"Número de valores faltantes (NaN): {nan_count}")
print(f"Percentual de valores faltantes: {percentual_nan:.2f}%") # Deve ser próximo de 30%

import matplotlib.pyplot as plt

# Carregar os dados dos cenários normal e anômalo
dados_normal = np.load('dados_gerados/cenario_normal.npy')
dados_anomalo = np.load('dados_gerados/cenario_anomalo.npy')
dados_normal_mcar = np.load('dados_gerados/cenario_normal_mcar_30p.npy')

# Definir qual amostra e qual sinal vamos plotar
amostra_idx = 0  # Primeira amostra
sinal_idx = 2    # Terceiro sinal (o que tem amplitude 2 no normal e 4 no anômalo)

# Criar o vetor de tempo para o eixo X
tempo = np.linspace(0, 10, 1000)

# Criar a figura para os gráficos
plt.figure(figsize=(15, 10))

# 1. Gráfico do Cenário Normal
plt.subplot(3, 1, 1) # 3 linhas, 1 coluna, 1º gráfico
plt.plot(tempo, dados_normal[amostra_idx, sinal_idx, :], label=f'Sinal {sinal_idx} - Cenário Normal')
plt.title('Comparação dos Cenários')
plt.ylabel('Amplitude')
plt.legend()
plt.grid(True)

# 2. Gráfico do Cenário Anômalo
plt.subplot(3, 1, 2) # 3 linhas, 1 coluna, 2º gráfico
plt.plot(tempo, dados_anomalo[amostra_idx, sinal_idx, :], color='red', label=f'Sinal {sinal_idx} - Cenário Anômalo')
plt.ylabel('Amplitude')
plt.legend()
plt.grid(True)

# 3. Gráfico do Cenário Normal com Dados Faltantes
plt.subplot(3, 1, 3) # 3 linhas, 1 coluna, 3º gráfico
plt.plot(tempo, dados_normal_mcar[amostra_idx, sinal_idx, :], color='green', linestyle='--', marker='o', markersize=2, label=f'Sinal {sinal_idx} - Normal com 30% Faltantes')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.legend()
plt.grid(True)


plt.tight_layout() # Ajusta o espaçamento
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# --- Configurações do Gráfico ---
# Vamos escolher UMA amostra e UM sinal para visualizar de forma clara.
# Se plotarmos tudo, o gráfico ficará ilegível.
AMOSTRA_PARA_PLOTAR = 0  # A primeira amostra (de 0 a 19)
SINAL_PARA_PLOTAR = 1   # O segundo sinal (de 0 a 2), que tem frequência mais alta

# Nomes dos arquivos que vamos carregar
arquivos = {
    'Cenário Normal (20% Faltante)': 'dados_gerados/cenario_normal_mcar_20p.npy',
    'Cenário Normal - Alt. (20% Faltante)': 'dados_gerados/cenario_normal_alt_mcar_20p.npy',
    'Cenário Anômalo (20% Faltante)': 'dados_gerados/cenario_anomalo_mcar_20p.npy'
}

# Criar uma figura que conterá nossos 3 gráficos (3 linhas, 1 coluna)
# `figsize` define o tamanho da imagem final.
# `sharex=True` faz com que todos os gráficos compartilhem o mesmo eixo X (tempo).
fig, axes = plt.subplots(3, 1, figsize=(16, 10), sharex=True)

# Título geral para a figura inteira
fig.suptitle(f'Visualização dos Cenários com 20% de Dados Faltantes (Amostra {AMOSTRA_PARA_PLOTAR}, Sinal {SINAL_PARA_PLOTAR})', fontsize=16)

# Vetor de tempo para o eixo X
tempo = np.linspace(0, 10, 1000)

# Loop para carregar e plotar cada cenário
for i, (titulo, caminho) in enumerate(arquivos.items()):
    try:
        # Carrega o arquivo .npy
        dados = np.load(caminho)

        # Extrai a série temporal específica que queremos plotar
        serie_temporal = dados[AMOSTRA_PARA_PLOTAR, SINAL_PARA_PLOTAR, :]

        # Seleciona o subplot correto (axes[0], axes[1], ou axes[2])
        ax = axes[i]

        # Plota os dados
        # O `linestyle='--'` e `marker='.'` ajudam a visualizar os pontos
        # e os "buracos" onde os dados estão faltando.
        ax.plot(tempo, serie_temporal, linestyle='--', marker='.', markersize=3, label=titulo)

        # Configurações do gráfico individual
        ax.set_title(titulo)
        ax.set_ylabel('Amplitude')
        ax.grid(True)

    except FileNotFoundError:
        print(f"ERRO: Arquivo não encontrado em '{caminho}'")
        print("Certifique-se de que a pasta 'dados_gerados' está no lugar certo.")
        # Preenche o gráfico com uma mensagem de erro
        ax = axes[i]
        ax.text(0.5, 0.5, f'Arquivo não encontrado:\n{caminho}',
                horizontalalignment='center', verticalalignment='center',
                fontsize=12, color='red', transform=ax.transAxes)


# Adiciona o rótulo do eixo X apenas no último gráfico
axes[-1].set_xlabel('Tempo (s)')

# Ajusta o layout para evitar que os títulos se sobreponham
plt.tight_layout(rect=[0, 0, 1, 0.96]) # `rect` ajusta o espaço para o título principal

# Mostra o gráfico
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# --- Configurações ---
# Caminho para o arquivo do cenário normal completo
ARQUIVO_CENARIO_NORMAL = 'dados_gerados/cenario_normal.npy'

# Vamos escolher uma única amostra para visualizar seus 3 sinais.
# A primeira amostra (índice 0) é uma boa escolha.
AMOSTRA_PARA_PLOTAR = 0

# --- Início do Código ---
try:
    # Carrega o arquivo .npy do cenário normal
    dados_normal = np.load(ARQUIVO_CENARIO_NORMAL)

    # Extrai apenas a primeira amostra para a visualização.
    # A forma (shape) resultante será (3, 1000), contendo nossos 3 sinais.
    amostra_selecionada = dados_normal[AMOSTRA_PARA_PLOTAR, :, :]

    # Vetor de tempo para o eixo X (de 0 a 10 segundos, com 1000 pontos)
    tempo = np.linspace(0, 10, 1000)

    # --- Plotagem ---
    # Cria a figura e os eixos para o gráfico
    plt.figure(figsize=(16, 8))

    # Nomes para a legenda, correspondendo à ordem de criação
    legendas = [
        'Sinal 0 (Amp: 1.0, Freq: 10 rad/s)',
        'Sinal 1 (Amp: 0.5, Freq: 50 rad/s)',
        'Sinal 2 (Amp: 2.0, Freq: 25 rad/s)'
    ]

    # Loop para plotar cada um dos 3 sinais
    for i in range(amostra_selecionada.shape[0]): # O loop irá de 0 a 2
        plt.plot(tempo, amostra_selecionada[i, :], label=legendas[i])

    # Adiciona títulos, legendas e grade para melhor visualização
    plt.title(f'Visualização dos 3 Sinais da Amostra {AMOSTRA_PARA_PLOTAR} (Cenário Normal)', fontsize=16)
    plt.xlabel('Tempo (s)', fontsize=12)
    plt.ylabel('Amplitude', fontsize=12)
    plt.legend(fontsize=10)
    plt.grid(True, which='both', linestyle='--', linewidth=0.5)
    plt.show()

except FileNotFoundError:
    print(f"ERRO: Arquivo não encontrado em '{ARQUIVO_CENARIO_NORMAL}'")
    print("Por favor, certifique-se de que você executou o script de geração de dados primeiro.")