# -*- coding: utf-8 -*-
"""preprocessamento-isa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Fcxyb6-rFO7ajFJHHztewQdEITpKQfV

# **Tratamento dos Dados**

## **Extrair dados**

- `A0`

Monitorar vibrações na carcaça do motor.

- `A1`

Captar vibrações radiais na engrenagem de entrada.

- `A2`

Captar vibrações verticais na engrenagem de entrada.

- `A3`

Monitorar a vibração na saída do redutor.

- `A4`

Analisar a saúde dos rolamentos da engrenagem.

- `A5`

Analisar a saúde dos rolamentos do motor.

**CÓDIGO**
"""

import os
import pandas as pd
import numpy as np
from tqdm import tqdm
from sklearn.preprocessing import StandardScaler, RobustScaler
from google.colab import drive
import matplotlib.pyplot as plt


drive.mount('/content/drive', force_remount=True)

"""## **Pre-processamento antes de separar as janelas**

frequência de amostragem de 50 kHz (50.000 amostras por segundo)

uma janela de 2048 pontos equivale a uma duração de 0,04 segundos



---


**POR QUE POTÊNCIA DE 2?**

2048 é uma potência exata de base 2 ($2^{11}$).

Bibliotecas de Deep Learning (como PyTorch e TensorFlow) e algoritmos de processamento de sinais (como a Transformada Rápida de Fourier - FFT) são otimizados a nível de hardware para trabalhar com matrizes que tenham tamanhos em potências de 2.

* **Overlap** é o quanto uma janela se sobrepõe à próxima.
"""

import os
import scipy.io
import pandas as pd
import numpy as np


class ProcessadorAcelerometro:
    def __init__(self, caminho_arquivo, fs=50000):
        self.caminho = caminho_arquivo
        self.fs = fs
        self.df = self.extrair_dados()

    def extrair_dados(self):
        try:
            mat = scipy.io.loadmat(self.caminho)
            dados_struct = mat['data'][0, 0]['Analog50k']

            campos = [
                'TDMSAnalog50kAcelerometer0', 'TDMSAnalog50kAcelerometer1',
                'TDMSAnalog50kAcelerometer2', 'TDMSAnalog50kAcelerometer3',
                'TDMSAnalog50kAcelerometer4', 'TDMSAnalog50kAcelerometer5'
            ]
            nomes_colunas = ['A0_Motor', 'A1_Pinion_H', 'A2_Pinion_V', 'A3_Gear_V', 'A4_Bearing_G', 'A5_Bearing_M']

            lista_sinais = []
            for campo in campos:
                sinal_bruto = dados_struct[campo][0, 0].flatten()
                lista_sinais.append(sinal_bruto)

            matriz_dados = np.array(lista_sinais, dtype=float).T
            df = pd.DataFrame(matriz_dados, columns=nomes_colunas)
            df['Tempo_s'] = np.arange(len(df)) / self.fs
            return df
        except Exception as e:
            print(f"Erro detalhado em {self.caminho}: {str(e)}")
            return pd.DataFrame()

base_dir = '/content/drive/MyDrive/IC_PIBIC/INICIAÇÃO CIENTÍFICA'
pasta_destino = '/content/drive/MyDrive/IC_PIBIC/acelerometros_processados'

if not os.path.exists(pasta_destino):
    os.makedirs(pasta_destino)

arquivos_alvo = {
    'R1F1L1P1': f'{base_dir}/P1/R1F1L1P1.mat',
    'R1F1L1P2': f'{base_dir}/P2/R1F1L1P2.mat',
    'R1F1L1P10': f'{base_dir}/P10/R1F1L1P10.mat'
}

print("Iniciando extração dos dados brutos (.mat para .parquet)...\n")

for nome_arquivo, caminho_mat in arquivos_alvo.items():
    print(f"Buscando {nome_arquivo} em: {caminho_mat}")

    if not os.path.exists(caminho_mat):
        print(f"  ❌ ERRO: Arquivo não encontrado no Drive.\n")
        continue

    exp = ProcessadorAcelerometro(caminho_mat)

    if not exp.df.empty:
        caminho_parquet = os.path.join(pasta_destino, f"{nome_arquivo}_bruto.parquet")
        exp.df.to_parquet(caminho_parquet, index=False)
        print(f"  ✅ Sucesso! Convertido e salvo em: {caminho_parquet}\n")
    else:
        print(f"  ❌ Falha ao extrair dados de {nome_arquivo}. O arquivo pode estar corrompido.\n")

print("Extração concluída!")

class Preprocessamento:
    def __init__(self, tamanho_janela=2048, overlap=0.5, tipo_scaler='robust'):
        self.tamanho_janela = tamanho_janela
        self.overlap = overlap
        self.tipo_scaler = tipo_scaler.lower()

        #  de normalização
        if self.tipo_scaler == 'standard':
            self.scaler = StandardScaler()
        elif self.tipo_scaler == 'robust':
            self.scaler = RobustScaler()
        else:
            raise ValueError("O parâmetro tipo_scaler deve ser 'standard' ou 'robust'.")

    def separar_tempo_sensores(self, df):
        tempo = df.iloc[:, -1].to_numpy()
        dados = df.iloc[:, :-1].to_numpy()
        return dados, tempo

    def divisao_temporal(self, dados, proporcao_treino=0.8):
        indice_corte = int(len(dados) * proporcao_treino)
        treino = dados[:indice_corte]
        teste = dados[indice_corte:]
        return treino, teste

    def normalizar_dados(self, treino, teste):
        # Aprende os parâmetros APENAS do treino
        self.scaler.fit(treino)

        # Aplica a transformação em ambos
        treino_norm = self.scaler.transform(treino)
        teste_norm = self.scaler.transform(teste)

        return treino_norm, teste_norm

    def criar_janelas(self, dados):
        passo = int(self.tamanho_janela * (1 - self.overlap))
        janelas = []

        # percorre capturando os blocos e transformando em tensores
        for inicio in range(0, len(dados) - self.tamanho_janela + 1, passo):
            fim = inicio + self.tamanho_janela
            janelas.append(dados[inicio:fim])

        return np.array(janelas)

    def executar_pipeline_arquivo_unico(self, df):
        dados, _ = self.separar_tempo_sensores(df)
        treino_raw, teste_raw = self.divisao_temporal(dados, proporcao_treino=0.8)
        treino_norm, teste_norm = self.normalizar_dados(treino_raw, teste_raw)
        X_treino = self.criar_janelas(treino_norm)
        X_teste = self.criar_janelas(teste_norm)
        return X_treino, X_teste

pasta_origem = '/content/drive/MyDrive/IC_PIBIC/acelerometros_processados'
pasta_destino = '/content/drive/MyDrive/ecomp/IC/IC_PIBIC/tensores_prontos'

if not os.path.exists(pasta_destino):
    os.makedirs(pasta_destino)

arquivos_alvo = [
    'R1F1L1P1_bruto.parquet',
    'R1F1L1P2_bruto.parquet',
    'R1F1L1P10_bruto.parquet'
]

prep = Preprocessamento(tamanho_janela=2048, overlap=0.5, tipo_scaler='robust')

print(f"Iniciando o processamento dos {len(arquivos_alvo)} arquivos do experimento...\n")

for arquivo in tqdm(arquivos_alvo, desc="Processando tensores"):
    prefixo = arquivo.replace('_bruto.parquet', '')
    caminho_completo = os.path.join(pasta_origem, arquivo)

    try:
        if not os.path.exists(caminho_completo):
            print(f"\n[Aviso] Arquivo não encontrado na pasta origem: {arquivo}")
            continue

        # Carrega o arquivo parquet
        df = pd.read_parquet(caminho_completo)

        X_train, X_test = prep.executar_pipeline_arquivo_unico(df)

        # Salva os tensores em formato .npy
        np.save(os.path.join(pasta_destino, f"{prefixo}_robust_X_train.npy"), X_train)
        np.save(os.path.join(pasta_destino, f"{prefixo}_robust_X_test.npy"), X_test)

    except Exception as e:
        print(f"\nErro no arquivo {arquivo}: {e}")

print("\n\n✅ Tensores P1, P2 e P10 processados")

pasta_destino = '/content/drive/MyDrive/ecomp/IC/IC_PIBIC/tensores_prontos'

try:
    p1_test = np.load(os.path.join(pasta_destino, 'R1F1L1P1_robust_X_test.npy'))
    p2_test = np.load(os.path.join(pasta_destino, 'R1F1L1P2_robust_X_test.npy'))
    p10_test = np.load(os.path.join(pasta_destino, 'R1F1L1P10_robust_X_test.npy'))
    print("✅ Tensores carregados com sucesso para a EDA!")
except FileNotFoundError as e:
    print(f"❌ Erro ao carregar: {e}")
    print("Verifique se o script anterior terminou de rodar e salvou os arquivos corretamente.")

# PARTE 1: Visualização do Sinal no Tempo
sensor_idx = 2
janela_idx = 10 # janela aleatória
plt.figure(figsize=(16, 6))

plt.plot(p1_test[janela_idx, :, sensor_idx], label='P1 (Comportamento Normal)', color='#2ca02c', alpha=0.9, linewidth=1.5)
plt.plot(p2_test[janela_idx, :, sensor_idx], label='P2 (Anomalia Nível 2)', color='#ff7f0e', alpha=0.7, linewidth=1.5)
plt.plot(p10_test[janela_idx, :, sensor_idx], label='P10 (Anomalia Nível 10)', color='#d62728', alpha=0.7, linewidth=1.5)

plt.title(f"Comparação do Formato de Onda - Sensor A2 (Janela {janela_idx})", fontsize=15, fontweight='bold')
plt.xlabel("Tempo (Amostras da Janela de 2048 pontos)", fontsize=12)
plt.ylabel("Amplitude Normalizada (RobustScaler)", fontsize=12)
plt.axhline(0, color='black', linewidth=0.8, linestyle='--')
plt.legend(loc='upper right', fontsize=11)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()


# PARTE 2: Comparação Energia RMS
print("\n" + "="*70)
print("COMPARAÇÃO DE ENERGIA VIBRACIONAL (Média RMS do Teste)")
print("="*70)

nomes_sensores = ['A0_Motor', 'A1_Pinion_H', 'A2_Pinion_V', 'A3_Gear_V', 'A4_Bearing_G', 'A5_Bearing_M']

# Função auxiliar para calcular o RMS médio de todas as janelas para cada sensor
def calcular_rms_medio(tensor):
    # tensor.shape = (janelas, 2048, 6)
    # Eleva ao quadrado, tira a média no eixo do tempo (2048), tira a raiz, depois a média das janelas
    rms_por_janela = np.sqrt(np.mean(tensor**2, axis=1))
    rms_medio = np.mean(rms_por_janela, axis=0)
    return rms_medio

rms_p1 = calcular_rms_medio(p1_test)
rms_p2 = calcular_rms_medio(p2_test)
rms_p10 = calcular_rms_medio(p10_test)


print(f"{'Sensor':<15} | {'P1 (Normal)':<12} | {'P2 (Falha)':<12} | {'P10 (Falha Grave)':<15}")
print("-" * 60)
for i, nome in enumerate(nomes_sensores):
    print(f"{nome:<15} | {rms_p1[i]:<12.4f} | {rms_p2[i]:<12.4f} | {rms_p10[i]:<15.4f}")
print("="*60)

"""A rede neural (MTSA) exige os dados nesse formato de `(Número de Janelas, 2048, 6). ` para conseguir analisar blocos de $2048$ instantes de tempo cruzando a informação dos $6$ sensores simultaneamente.

**O que o MTSA precisa?**

Modelos de Multivariate Time Series Anomaly Detection fazem:

Fluxo:


```
Dados → Modelo → Reconstrução → Erro → Score de Anomalia
```
"""